### ISSUE TITLE
verify와 mqtt_key 값이 안나옵니다

### ISSUE THREAD

**Issue by iykkim** [SeongSikChae/PowerManagerConfig#1]
안녕하세요.

다른 문의 드립니다.

PowerManagerConfig 파일 실행 단계에서 네트워크 정상화 후 Enter 입력을 하면 verify:   mqtt_key:  로 나오고 아무 값이 안 나오는 상태인데 어떻게 하면 될까요?

아래는 명령문 실행 내용입니다.
(실제 내용에서 암호, mac주소, id 부분만 ****로 변경)

PS D:\Utils\Home Automation\PowerMgr서버> ./PowerManagerConfig --host 192.168.244.1 --port 5000 --api_server_addr https://192.168.1.21:18443 --web_server_addr https://192.168.1.21 --clientCertificate D:\PowerManager\Certificate\newcerts\C.p12 --clientCertificatePassword ****
[::ffff:192.168.244.1]:5000 Connected
Mode V1 (B540 <= v1.01.26) or V2 (B540 == v1.01.28) or V3 (B540 == v1.01.30) or V4 (B550) (default V1): V3
[DUT->PC] START_OK:****#
SSID: YKHome2
Wifi Password: ****
UserId: ****@gmail.com
Model: B540-W
Mqtt Topic: dwd
Push: {"mac":"****","api_server_addr":"dwapi.dawonai.com","api_server_port":"18443","server_addr":"dwmqtt.dawonai.com","server_port":"8883","ssl_support":"yes","ssid":"YKHome2","pass":"****","user_id":"****@gmail.com","company":"DAWONDNS","model":"B540-W","lati":"37.6523018","long":"127.0622559","topic":"dwd"}
Send: 321 Byte.
{"mac":"****","respone":"OK"}
37
{"mac":"****","respone":"OK"}
네트워크를 정상화 시킨 후 Enter를 입력하세요.
verify:  mqtt_key:

**Comment by SeongSikChae** [comment]
user_id가 잘못되었습니다. user_id 는 AIPM 앱에서 XXX@XXX.XXX/XXX 까지 전부 입력하셔야 합니다.
![1](https://user-images.githubusercontent.com/55735227/158025691-0247818e-6d20-4aaa-93f9-8ab17f63a550.jpg)

**Comment by iykkim** [comment]
안녕하세요,

아침에 작은 헤프닝(서버 재시작 후 페이지 안 열리던 문제)이 있었으나 해결하고, 알려주신 대로 aipm 앱에 나오는 id로 입력하고 진행하자 mqtt_key 값이 잘 나오고 나머지도 메뉴얼대로 모두 진행되었습니다.

지금은 마침내 1.01.30 펌웨어 적용 상태의 B540-W 스위치 하나를 PowerManager 로컬 서버에 연결해서 잘 작동시키고 있습니다.

다시 한번 좋은 프로그램 만들어서 배포해 주신 점 감사드립니다.

아래는 관리 페이지에서 등록과 실행 중인 모습입니다.

![등록 실행 화면](https://user-images.githubusercontent.com/52940190/158040789-8d257197-f7eb-4e9d-aa40-74c36caaa225.jpg)

그럼 편안한 휴일 보내세요~
